language: r
cache: packages
latex: false
fortran: false
pandoc: false

R: 3.4

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.3
      brew_packages: rust
    - os: osx
      osx_image: xcode7.3
      brew_packages: rust

addons:
  apt:
    packages:
      - cargo
